description: This PWA can be used to sign up for the Omaha & Lincoln area NebraskaJS meetups. Come sign up and view the current proposals.
title: NebraskaJS Speaker Signup
keywords:
  - javascript
  - nebraska
  - omaha
  - lincoln
  - nebraskajs
  - frontend
  - meetup
  - local meetup
  - proposals
  - speakers
